# Generated by Django 4.2.8 on 2024-01-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_customuser_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, help_text='Enter your full name', max_length=255, verbose_name='Full Name'),
        ),
    ]
