# Generated by Django 4.2.8 on 2024-01-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('tavg', models.FloatField()),
                ('rh_avg', models.FloatField()),
                ('ff_avg', models.FloatField()),
            ],
        ),
    ]
